[mgr]
show_hidden = true

[opener]
edit = [
	{ run = "helix %s", block = true, for = "unix" },
]
open = [
	{ run = "xdg-open %s", block = true, for = "unix" },
]

[open]
rules = [
	{ mime = "inode/directory", use = ["open"] },
	{ mime = "inode/empty", use = "edit" },
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
	{ url = "*.json", use = "edit" },
	{ url = "*.html", use = [ "open", "edit" ] },
	{ url = "*.pdf", use = "open" },
]

[fs]
prefetch_workers = 8

[vfs]
cache_size = 52428800

[preview]
max_depth = 3
skep_large_files = true

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
