os:
  edit: "hx {{filename}}"
git:
  pagers:
    - pager: delta --light --paging=never --line-numbers
gui:
  timeFormat: 2006-01-02
  shortTimeFormat: 15:04
  theme:
    selectedLineBgColor:
      - reverse
